<template>
  <div>
    <h6>&copy</h6>
    <script
      type="text/javascript"
      src="//inpage-push.com/400/4432264"
      data-cfasync="false"
      async="async"
    ></script>
  </div>
</template>
